// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjJ1oGMhsgFbeBoPmKYypOin4-YKDtvU',
    appId: '1:223594003555:web:2d3ac2adadf17b099ecc56',
    messagingSenderId: '223594003555',
    projectId: 'budget-tracker-xz',
    authDomain: 'budget-tracker-xz.firebaseapp.com',
    storageBucket: 'budget-tracker-xz.firebasestorage.app',
    measurementId: 'G-X3NRSPWJ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpzcdwqqVEIA4fiMbJIPDRdkGHz3yXxM',
    appId: '1:223594003555:android:6facebc57105f1cf9ecc56',
    messagingSenderId: '223594003555',
    projectId: 'budget-tracker-xz',
    storageBucket: 'budget-tracker-xz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzuU-_enMditD7V1Ih8Xwh510Ju4XR0s0',
    appId: '1:223594003555:ios:0a30af03e355c8939ecc56',
    messagingSenderId: '223594003555',
    projectId: 'budget-tracker-xz',
    storageBucket: 'budget-tracker-xz.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzuU-_enMditD7V1Ih8Xwh510Ju4XR0s0',
    appId: '1:223594003555:ios:0a30af03e355c8939ecc56',
    messagingSenderId: '223594003555',
    projectId: 'budget-tracker-xz',
    storageBucket: 'budget-tracker-xz.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXjJ1oGMhsgFbeBoPmKYypOin4-YKDtvU',
    appId: '1:223594003555:web:9f56a66739dd89ad9ecc56',
    messagingSenderId: '223594003555',
    projectId: 'budget-tracker-xz',
    authDomain: 'budget-tracker-xz.firebaseapp.com',
    storageBucket: 'budget-tracker-xz.firebasestorage.app',
    measurementId: 'G-LVNXQSE6NT',
  );

}